{{- if .Values.isJob }}
apiVersion: batch/v1
kind: Job
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ include "pycryptobot.fullname" . }}
  labels:
    {{- include "pycryptobot.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.isJob }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.telegramBot.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
        {{- include "pycryptobot.selectorLabels" . | nindent 6 }}
  {{- else }}
  parallelism: 1
  completions: 1
  {{- end }}
  template:
    metadata:
      annotations:
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "pycryptobot.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.isJob }}
      restartPolicy: OnFailure
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pycryptobot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
            - name: config
              mountPath: /app/scanner.json
              subPath: scanner.json
            - name: api-keys
              mountPath: /app/keys
              readOnly: true
            - name: config
              mountPath: /app/operator.defaults.yaml
              subPath: operator.defaults.yaml
            {{- if .Values.telegramBot.persistence.enabled }}
            - name: tg-data
              mountPath: /app/telegram_data
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 8 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ default (include "pycryptobot.fullname" .) .Values.existingConfig }}
            items:
            - key: config.json
              path: config.json
            - key: scanner.json
              path: scanner.json
            - key: operator.defaults.yaml
              path: operator.defaults.yaml
        - name: api-keys
          secret:
            secretName: {{ default (include "pycryptobot.fullname" .) .Values.existingSecret }}
            items:
            - key: binance.key
              path: binance.key
            - key: coinbasepro.key
              path: coinbasepro.key
            - key: kucoin.key
              path: kucoin.key
        {{- if .Values.telegramBot.persistence.enabled }}
        - name: tg-data
          persistentVolumeClaim:
            {{- if .Values.telegramBot.persistence.existingClaimName }}
            claimName: {{ .Values.telegramBot.persistence.existingClaimName }}
            {{- else }}
            claimName: {{ template "pycryptobot.fullname" . }}-telegram-data
            {{- end }}
        {{- end }}
        {{- if .Values.extraVolumes }}
          {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
