{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pycryptobot.serviceAccountName" . }}
  labels:
    {{- include "pycryptobot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.useK8SOperator }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pycryptobot-all
rules:
- apiGroups: ["charts.pycryptobot.org"]
  resources: ["pycryptobots"]
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pycryptobot-all
subjects:
- kind: ServiceAccount
{{- if .Values.serviceAccount.create }}
  name: {{ template "pycryptobot.serviceAccountName" . }}
{{- else }}
  name: default
{{- end }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pycryptobot-all
  apiGroup: rbac.authorization.k8s.io
{{- end }}